# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcPWD <- function(x) {
    .Call(`_tdnn_calcPWD`, x)
}

sweep <- function(x, y, margin) {
    .Call(`_tdnn_sweep`, x, y, margin)
}

Astar <- function(d) {
    .Call(`_tdnn_Astar`, d)
}

BCDCOR <- function(x, y) {
    .Call(`_tdnn_BCDCOR`, x, y)
}

dcor_t_test <- function(x, y) {
    .Call(`_tdnn_dcor_t_test`, x, y)
}

feature_screening <- function(x, y, alpha = 0.001) {
    .Call(`_tdnn_feature_screening`, x, y, alpha)
}

de_dnn_st <- function(X, Y, X_test, s_sizes, c, W0_ = NULL) {
    .Call(`_tdnn_de_dnn_st`, X, Y, X_test, s_sizes, c, W0_)
}

best_s <- function(estimate_matrix) {
    .Call(`_tdnn_best_s`, estimate_matrix)
}

tuning_st <- function(s_seq, X, Y, X_test, c, W0_) {
    .Call(`_tdnn_tuning_st`, s_seq, X, Y, X_test, c, W0_)
}

tuning_test <- function(s_seq, X, Y, X_test, bc_p, W0_) {
    invisible(.Call(`_tdnn_tuning_test`, s_seq, X, Y, X_test, bc_p, W0_))
}

de_dnn <- function(X, Y, X_test, s_sizes, c, W0_ = NULL) {
    .Call(`_tdnn_de_dnn`, X, Y, X_test, s_sizes, c, W0_)
}

tuning <- function(X, Y, X_test, c, W0_ = NULL) {
    .Call(`_tdnn_tuning`, X, Y, X_test, c, W0_)
}

submat_rcpp <- function(X, condition) {
    .Call(`_tdnn_submat_rcpp`, X, condition)
}

matrix_subset_idx_rcpp <- function(x, y) {
    .Call(`_tdnn_matrix_subset_idx_rcpp`, x, y)
}

bootstrap_cpp <- function(X, X_test, Y, W, W0, s_choice_0, s_choice_1, c = 0.33, B = 1000L) {
    .Call(`_tdnn_bootstrap_cpp`, X, X_test, Y, W, W0, s_choice_0, s_choice_1, c, B)
}

