# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

de_dnn_st <- function(X, Y, X_test, s_sizes, c, W0_ = NULL) {
    .Call(`_tdnn_de_dnn_st`, X, Y, X_test, s_sizes, c, W0_)
}

best_s <- function(estimate_matrix) {
    .Call(`_tdnn_best_s`, estimate_matrix)
}

tuning_st <- function(s_seq, X, Y, X_test, c, W0_) {
    .Call(`_tdnn_tuning_st`, s_seq, X, Y, X_test, c, W0_)
}

tuning_test <- function(s_seq, X, Y, X_test, bc_p, W0_) {
    invisible(.Call(`_tdnn_tuning_test`, s_seq, X, Y, X_test, bc_p, W0_))
}

de_dnn <- function(X, Y, X_test, s_sizes, c, W0_ = NULL) {
    .Call(`_tdnn_de_dnn`, X, Y, X_test, s_sizes, c, W0_)
}

tuning <- function(X, Y, X_test, c, W0_ = NULL) {
    .Call(`_tdnn_tuning`, X, Y, X_test, c, W0_)
}

