# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tdnn_st_boot <- function(X, Y, X_test, weight_mat_s_1, weight_mat_s_2, c, n_prop) {
    .Call(`_tdnn_tdnn_st_boot`, X, Y, X_test, weight_mat_s_1, weight_mat_s_2, c, n_prop)
}

bootstrap_cpp_mt <- function(X, Y, X_test, s_1, c, n_prop, B, W0_) {
    .Call(`_tdnn_bootstrap_cpp_mt`, X, Y, X_test, s_1, c, n_prop, B, W0_)
}

bootstrap_trt_effect_cpp_mt <- function(X, Y, W, X_test, s_choice_trt, s_choice_ctl, c, n_prop, B, W0_ = NULL) {
    .Call(`_tdnn_bootstrap_trt_effect_cpp_mt`, X, Y, W, X_test, s_choice_trt, s_choice_ctl, c, n_prop, B, W0_)
}

tdnn <- function(X, Y, X_test, c, n_prop, s_1_val, s_2_val, W0_) {
    .Call(`_tdnn_tdnn`, X, Y, X_test, c, n_prop, s_1_val, s_2_val, W0_)
}

de_dnn <- function(X, Y, X_test, s_sizes, c, n_prop, W0_ = NULL) {
    .Call(`_tdnn_de_dnn`, X, Y, X_test, s_sizes, c, n_prop, W0_)
}

tuning <- function(X, Y, X_test, c, n_prop, W0_) {
    .Call(`_tdnn_tuning`, X, Y, X_test, c, n_prop, W0_)
}

tuning_est <- function(X, Y, X_test, c, n_prop, W0_ = NULL) {
    .Call(`_tdnn_tuning_est`, X, Y, X_test, c, n_prop, W0_)
}

tdnn_ord_y <- function(X, Y, X_test, ordered_Y, s_1, c, n_prop) {
    .Call(`_tdnn_tdnn_ord_y`, X, Y, X_test, ordered_Y, s_1, c, n_prop)
}

tuning_ord_Y <- function(X, Y, X_test, ordered_Y, c, n_prop) {
    .Call(`_tdnn_tuning_ord_Y`, X, Y, X_test, ordered_Y, c, n_prop)
}

make_ordered_Y_mat_debug <- function(X, Y, X_test, B_NN = 20L) {
    .Call(`_tdnn_make_ordered_Y_mat_debug`, X, Y, X_test, B_NN)
}

make_B_NN_estimates <- function(X, Y, X_test_i, top_B, s_tmp, c, n_prop = 0.5, B_NN = 20L, scale_p = 1, debug = FALSE) {
    .Call(`_tdnn_make_B_NN_estimates`, X, Y, X_test_i, top_B, s_tmp, c, n_prop, B_NN, scale_p, debug)
}

choose_s_1_val <- function(tuned_mse, s_1_vec_tmp) {
    .Call(`_tdnn_choose_s_1_val`, tuned_mse, s_1_vec_tmp)
}

tune_de_dnn_no_dist_cpp <- function(X, Y, X_test, W0_, c = 2, B_NN = 20L, scale_p = 1, n_prop = 0.5, estimate_variance = FALSE, bootstrap_iter = 500L, debug = FALSE) {
    .Call(`_tdnn_tune_de_dnn_no_dist_cpp`, X, Y, X_test, W0_, c, B_NN, scale_p, n_prop, estimate_variance, bootstrap_iter, debug)
}

tdnn_reg_cpp <- function(X, Y, X_test, c, n_prop, s_1_val, bootstrap_iter, estimate_variance, verbose, W0_) {
    .Call(`_tdnn_tdnn_reg_cpp`, X, Y, X_test, c, n_prop, s_1_val, bootstrap_iter, estimate_variance, verbose, W0_)
}

tdnn_reg_cv_cpp <- function(X, Y, X_test, param_mat, n_prop, B, bootstrap_iter, estimate_variance, verbose, W0_) {
    .Call(`_tdnn_tdnn_reg_cv_cpp`, X, Y, X_test, param_mat, n_prop, B, bootstrap_iter, estimate_variance, verbose, W0_)
}

pt_mat_dist <- function(X, y) {
    .Call(`_tdnn_pt_mat_dist`, X, y)
}

make_ord_vec <- function(n) {
    .Call(`_tdnn_make_ord_vec`, n)
}

make_ordered_Y_vec <- function(X_train, X_val_vec, Y_train, n) {
    .Call(`_tdnn_make_ordered_Y_vec`, X_train, X_val_vec, Y_train, n)
}

make_param_estimate <- function(X_train, Y_train, X_val, ordered_Y, ord_arma, n, p, log_n, c, s_1_val, s_2_val, n_prop) {
    .Call(`_tdnn_make_param_estimate`, X_train, Y_train, X_val, ordered_Y, ord_arma, n, p, log_n, c, s_1_val, s_2_val, n_prop)
}

loo_test <- function(X, Y, X_test, param_mat, B, n_prop, W0, verbose) {
    .Call(`_tdnn_loo_test`, X, Y, X_test, param_mat, B, n_prop, W0, verbose)
}

tune_params <- function(X, Y, X_test, param_mat, B, n_prop, W0, verbose) {
    .Call(`_tdnn_tune_params`, X, Y, X_test, param_mat, B, n_prop, W0, verbose)
}

tune_params_debug <- function(X, Y, X_test, param_mat, B, n_prop, W0, verbose) {
    .Call(`_tdnn_tune_params_debug`, X, Y, X_test, param_mat, B, n_prop, W0, verbose)
}

r_like_order <- function(x, y) {
    .Call(`_tdnn_r_like_order`, x, y)
}

weight_mat_lfac_s_2_filter <- function(n, ord, s_vec, n_prop, is_s_2) {
    .Call(`_tdnn_weight_mat_lfac_s_2_filter`, n, ord, s_vec, n_prop, is_s_2)
}

round_modified <- function(x) {
    .Call(`_tdnn_round_modified`, x)
}

round_modified_vec <- function(x) {
    .Call(`_tdnn_round_modified_vec`, x)
}

arma_round <- function(x) {
    .Call(`_tdnn_arma_round`, x)
}

calc_dist_mat_cpp <- function(A, B) {
    .Call(`_tdnn_calc_dist_mat_cpp`, A, B)
}

